#! /bin/bash

set -e

remake() {
    rm -f "$1"
    mkfifo "$1"
}

base_dir="$HOME/.pista-in/.tmp"
mkdir -p "$base_dir"

fifo_time="$base_dir/time"
remake "$fifo_time"
fifo_mpd="$base_dir/mpd"
remake "$fifo_mpd"
fifo_vol="$base_dir/volume"
remake "$fifo_vol"
fifo_light="$base_dir/backlight"
remake "$fifo_light"
fifo_blue="$base_dir/bluetooth"
remake "$fifo_blue"
fifo_wifi="$base_dir/wifi"
remake "$fifo_wifi"
fifo_batt="$base_dir/battery"
remake "$fifo_batt"
fifo_upow="$base_dir/upower"
remake "$fifo_upow"
fifo_weather="$base_dir/weather"
remake "$fifo_weather"

wifi_if=$(iwconfig | grep -v '^lo' | awk '/^[^\ ]/ {print $1}')

./pista-sensor-time             > "$fifo_time"   &
./pista-sensor-mpd              > "$fifo_mpd"    &
./pista-sensor-volume           > "$fifo_vol"    &
./pista-sensor-backlight        > "$fifo_light"  &
./pista-sensor-bluetooth        > "$fifo_blue"   &
./pista-sensor-wifi "$wifi_if" 5 > "$fifo_wifi"   &
./pista-sensor-battery          > "$fifo_batt"   &
./pista-sensor-upower.rkt -i 30 > "$fifo_upow"   &
./pista-sensor-weather.rkt -i $(( 15 * 60)) KJFK > "$fifo_weather" &

pista \
    -l 0 \
    -i 0.5 \
    -s '  ' \
    "$fifo_upow"   11 60 \
    "$fifo_wifi"    8 10  \
    "$fifo_blue"    9 10  \
    "$fifo_light"  10  5   \
    "$fifo_vol"     8  5   \
    "$fifo_mpd"    17  5   \
    "$fifo_weather" 8 $(( 30 * 60 ))   \
    "$fifo_time"   21  2
