#! /bin/sh

count_powered_controllers() {
    echo 'show' | bluetoothctl | grep -c 'Powered: yes'
}

count_connected_devices() {
    echo 'paired-devices' \
    | bluetoothctl \
    | awk '{print $2}' \
    | xargs -I % bluetoothctl -- info % \
    | grep -c 'Connected: yes'
}

while :
do
    printf "ᛒ %d:%d\n" "$(count_powered_controllers)" "$(count_connected_devices)"
    sleep 5;
done
